import type {Locale,GameType} from '@ching/contracts';
const en={
 learn:'Learn',review:'Review',dictionary:'Dictionary',tagline:'A little play. A lot of Mandarin.',intro:'Build a daily habit, one small win at a time. Pick a path and let curiosity lead.',
 courses:'Your learning paths',courseHint:'Four ways to play. One new skill at a time.',xp:'XP earned',streak:'day streak',local:'Your progress stays on this device.',language:'Interface language',begin:'Start lesson',continue:'Continue',back:'Back to courses',goal:'Your goal',choose:'Choose a game',start:'Let’s play',skipCard:'Skip reference & play',round:'Round',of:'of',correct:'Correct!',incorrect:'Keep going — you’re learning.',next:'Next round',results:'See results',retry:'Retry',retrySame:'Retry same rounds',newRound:'Play new rounds',finish:'Session complete',passed:'Game completed',notPassed:'A little more practice',accuracy:'Accuracy',mistakes:'Words to revisit',noMistakes:'A clean round. Nicely done.',play:'Play audio',audioError:'Audio is unavailable. Use the transcript or retry playback.',transcript:'Show transcript',pinyin:'Show pinyin',skip:'Skip this round',seconds:'seconds left',untimed:'No timer',watch:'Watch stroke order',trace:'Trace with a pointer',identify:'Identify the character',traceDone:'Stroke practice complete. Choose the character below.',traceError:'Stroke data could not load. Retry to practice.',traceHint:'Watch the animation with the keyboard, or trace with a pointer. Both paths count.',loading:'Loading…',error:'Could not load this step. Please retry.',savingError:'Storage is unavailable or unreadable. Progress is kept for this visit; it may not survive a reload.',search:'Look up a word',searchHint:'Hanzi, pinyin, or English',noEntries:'No entries found in this curated dictionary.',reset:'Reset progress',resetConfirm:'Reset all progress on this device?',completed:'Completed',games:'games',reviewIntro:'Mistakes become your next small wins.',reviewEmpty:'No words waiting for review. Play a round to get started.',reference:'Quick reference',credits:'Content & credits',tone:'Tone Match',pinyinGame:'Pinyin Match',listen:'Listen & Pick',character:'Character Trace',toneHint:'Find the shape of a sound.',pinyinHint:'Connect characters and sounds.',listenHint:'Tune your ear to Mandarin.',characterHint:'Learn a character, stroke by stroke.',nextGame:'Next game',threshold:'Accuracy target',allGames:'Complete all four games to finish this lesson.',exit:'Leave session',confirmExit:'Leave this session? Unfinished rounds will not be saved.',study:'Practice',answer:'Choose an answer',home:'Ching home',emptyReview:'Review is clear',score:'Score',bonus:'Speed bonus',referenceHint:'Optional: take a breath and read your goal, or jump straight in.',notes:'Examples',timeNotice:'The timer starts when each round appears. Transcript and keyboard practice are always available.',showAnswer:'Correct answer'
};
type Copy=typeof en;
const hans:Copy={
 learn:'学习',review:'复习',dictionary:'词典',tagline:'玩一点，学更多中文。',intro:'每天一个小进步。选择学习路线，让好奇心带你前行。',
 courses:'你的学习路线',courseHint:'四种玩法，每次掌握一个小技能。',xp:'经验值',streak:'天连续学习',local:'学习进度保存在此设备上。',language:'界面语言',begin:'开始课程',continue:'继续',back:'返回课程',goal:'学习目标',choose:'选择游戏',start:'开始游戏',skipCard:'跳过说明并开始',round:'第',of:'／',correct:'答对了！',incorrect:'继续努力，你正在进步。',next:'下一题',results:'查看结果',retry:'重试',retrySame:'重试相同题目',newRound:'练习新题目',finish:'本轮完成',passed:'游戏完成',notPassed:'再练习一下',accuracy:'正确率',mistakes:'需要复习的词',noMistakes:'全部答对，做得好！',play:'播放音频',audioError:'音频暂不可用。请查看文字或重试播放。',transcript:'显示文字',pinyin:'显示拼音',skip:'跳过此题',seconds:'秒剩余',untimed:'不限时',watch:'观看笔顺',trace:'用指针描写',identify:'识别汉字',traceDone:'笔顺练习完成，请选择下方的汉字。',traceError:'笔顺数据加载失败，请重试。',traceHint:'用键盘观看动画，或用指针描写，两种方式都有效。',loading:'加载中…',error:'加载失败，请重试。',savingError:'存储不可用或数据损坏。本次进度可能无法在刷新后保留。',search:'查找词语',searchHint:'汉字、拼音或英语',noEntries:'精选词典中没有匹配的词条。',reset:'重置进度',resetConfirm:'重置此设备上的全部学习进度？',completed:'已完成',games:'个游戏',reviewIntro:'把错题变成下一次进步。',reviewEmpty:'暂无待复习词语，开始一轮游戏吧。',reference:'快速参考',credits:'内容与来源',tone:'声调配对',pinyinGame:'拼音配对',listen:'听音选择',character:'汉字描写',toneHint:'找出声音的形状。',pinyinHint:'连接汉字与读音。',listenHint:'练习中文听力。',characterHint:'一笔一画学习汉字。',nextGame:'下一个游戏',threshold:'目标正确率',allGames:'完成四个游戏即可完成本课。',exit:'离开游戏',confirmExit:'离开本轮游戏？未完成的题目不会保存。',study:'练习',answer:'选择答案',home:'Ching 首页',emptyReview:'暂无复习任务',score:'得分',bonus:'速度加分',referenceHint:'可先阅读目标，也可直接开始。',notes:'例句',timeNotice:'每题显示时开始计时。你随时可以查看文字或使用键盘练习。',showAnswer:'正确答案'
};
const hant:Copy={
 learn:'學習',review:'複習',dictionary:'詞典',tagline:'玩一點，學更多中文。',intro:'每天一個小進步。選擇學習路線，讓好奇心帶你前行。',
 courses:'你的學習路線',courseHint:'四種玩法，每次掌握一個小技能。',xp:'經驗值',streak:'天連續學習',local:'學習進度保存在此裝置上。',language:'介面語言',begin:'開始課程',continue:'繼續',back:'返回課程',goal:'學習目標',choose:'選擇遊戲',start:'開始遊戲',skipCard:'跳過說明並開始',round:'第',of:'／',correct:'答對了！',incorrect:'繼續努力，你正在進步。',next:'下一題',results:'查看結果',retry:'重試',retrySame:'重試相同題目',newRound:'練習新題目',finish:'本輪完成',passed:'遊戲完成',notPassed:'再練習一下',accuracy:'正確率',mistakes:'需要複習的詞',noMistakes:'全部答對，做得好！',play:'播放音訊',audioError:'音訊暫不可用。請查看文字或重試播放。',transcript:'顯示文字',pinyin:'顯示拼音',skip:'跳過此題',seconds:'秒剩餘',untimed:'不限時',watch:'觀看筆順',trace:'用指標描寫',identify:'識別漢字',traceDone:'筆順練習完成，請選擇下方的漢字。',traceError:'筆順資料載入失敗，請重試。',traceHint:'用鍵盤觀看動畫，或用指標描寫，兩種方式都有效。',loading:'載入中…',error:'載入失敗，請重試。',savingError:'儲存不可用或資料損壞。本次進度可能無法在重新整理後保留。',search:'查找詞語',searchHint:'漢字、拼音或英語',noEntries:'精選詞典中沒有符合的詞條。',reset:'重設進度',resetConfirm:'重設此裝置上的全部學習進度？',completed:'已完成',games:'個遊戲',reviewIntro:'把錯題變成下一次進步。',reviewEmpty:'暫無待複習詞語，開始一輪遊戲吧。',reference:'快速參考',credits:'內容與來源',tone:'聲調配對',pinyinGame:'拼音配對',listen:'聽音選擇',character:'漢字描寫',toneHint:'找出聲音的形狀。',pinyinHint:'連接漢字與讀音。',listenHint:'練習中文聽力。',characterHint:'一筆一畫學習漢字。',nextGame:'下一個遊戲',threshold:'目標正確率',allGames:'完成四個遊戲即可完成本課。',exit:'離開遊戲',confirmExit:'離開本輪遊戲？未完成的題目不會儲存。',study:'練習',answer:'選擇答案',home:'Ching 首頁',emptyReview:'暫無複習任務',score:'得分',bonus:'速度加分',referenceHint:'可先閱讀目標，也可直接開始。',notes:'例句',timeNotice:'每題顯示時開始計時。你隨時可以查看文字或使用鍵盤練習。',showAnswer:'正確答案'
};
export const copy=(locale:Locale):Copy=>locale==='en'?en:locale==='zh-Hans'?hans:hant;
export const gameName=(game:GameType,c:Copy)=>({'tone-match':c.tone,'pinyin-match':c.pinyinGame,'listen-pick':c.listen,'character-trace':c.character}[game]);
export const gameHint=(game:GameType,c:Copy)=>({'tone-match':c.toneHint,'pinyin-match':c.pinyinHint,'listen-pick':c.listenHint,'character-trace':c.characterHint}[game]);
